### ISSUE TITLE
The Readme needs updation

### ISSUE THREAD

**Issue by sachet-mittal** [MariusWirtz-cubewise/TM1py#18]
The installation steps in the README seems out of date as there is no TM1py.py file present.
It needs to be updated.

And the __init__.py file also seems to be missing.

**Comment by MariusWirtz** [comment]
Thanks for the Note. I will fix it!

If you want you know how to use TM1py check out the sampels. It's pretty straightforward.
https://github.com/MariusWirtz/TM1py/tree/master/Samples

**Comment by sachet-mittal** [comment]
Thanks!
Yeah sure.

Also, I think the __init__.py is also missing

But I am not so sure about the packaging stuff.

Thanks again.

**Comment by MariusWirtz-cubewise** [comment]
Issue solved. Thanks for the feedback!
