### ISSUE TITLE
Message logging?

### ISSUE THREAD

**Issue by dusherwo57** [MariusWirtz-cubewise/TM1py#22]
Marius, you refer to this in your writeup - but I haven't been able to locate any objects or services to handle this. Did it exist in earlier versions? 
I found a post on the SDK forum which shows the low level call:
https://www.ibm.com/developerworks/community/forums/html/topic?id=db478fa9-ea03-4e59-9d46-db67b5917118
quoting
http://localhost:8000/api/v1/MessageLog(Reverse=true)?$top=100 
which works in Postman.

**Comment by MariusWirtz** [comment]
Yeah it's in the ServerService.

`with TM1Service(address='', port=8001, user='admin', password='apple', ssl=True) as tm1:
    messages = tm1.server.get_last_message_log_entries(reverse=True, top=100)`

**Comment by dusherwo57** [comment]
Thanks! Apologies for missing it.



David Usherwood | Associate 
InfoCat, Riverside House, 27/29 Vauxhall Grove, London, SW8 1SY
p: 020 7735 7711 |  f: 020 7735 8811 
www.infocat.co.uk 
This message is private and confidential. If you have received this message in 
error, please notify us and remove it from your system.
InfoCat Ltd. is a limited company registered in England. Registered number: 
2843261. Registered office: 27-29 Vauxhall Grove, London, SW8 1SY.
